### ISSUE TITLE
关于generate_gld_list.py中的文件的continent_codes.csv和country_code.json怎么获取

### ISSUE THREAD

**Issue by ruyanyinian** [WesleyZhang1991/Google_Landmark_Retrieval_2021_2nd_Place_Solution#3]
如题，现在这两个文件是怎么获取的？

**Comment by WesleyZhang1991** [comment]
For country_code.json, we found it here https://storage.googleapis.com/gld-v2/data/train/country_codes.json. The download link can be found in this discussion: https://github.com/cvdfoundation/google-landmark/issues/20

For continent_codes.csv, check this https://checkme.online/olympics/continent.txt

**Comment by ruyanyinian** [comment]
thanks a lot
